/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.prototipo;

/**
 *
 * @author Maria Mata
 */
public class VentAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VentAdministrador
     */
    public VentAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn = new javax.swing.JPanel();
        jpCelula = new javax.swing.JPanel();
        lblCelula = new javax.swing.JLabel();
        jpRedes = new javax.swing.JPanel();
        lblRedes = new javax.swing.JLabel();
        jpPersonas = new javax.swing.JPanel();
        lblPErsonas = new javax.swing.JLabel();
        jpLideres = new javax.swing.JPanel();
        lblLideres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn.setBackground(new java.awt.Color(52, 73, 94));

        jpCelula.setBackground(new java.awt.Color(52, 152, 219));
        jpCelula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCelula.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblCelula.setForeground(new java.awt.Color(255, 255, 255));
        lblCelula.setText("CELULAS");
        jpCelula.add(lblCelula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jpRedes.setBackground(new java.awt.Color(52, 152, 219));
        jpRedes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRedes.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblRedes.setForeground(new java.awt.Color(255, 255, 255));
        lblRedes.setText("REDES");
        jpRedes.add(lblRedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jpPersonas.setBackground(new java.awt.Color(52, 152, 219));
        jpPersonas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPErsonas.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblPErsonas.setForeground(new java.awt.Color(255, 255, 255));
        lblPErsonas.setText("PERSONAS");
        jpPersonas.add(lblPErsonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jpLideres.setBackground(new java.awt.Color(52, 152, 219));
        jpLideres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLideres.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblLideres.setForeground(new java.awt.Color(255, 255, 255));
        lblLideres.setText("LIDERES");
        jpLideres.add(lblLideres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLayout.createSequentialGroup()
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jpCelula, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jpRedes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addComponent(jpLideres, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(107, 107, 107))
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpCelula, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLideres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpRedes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpCelula;
    private javax.swing.JPanel jpLideres;
    private javax.swing.JPanel jpPersonas;
    private javax.swing.JPanel jpRedes;
    private javax.swing.JLabel lblCelula;
    private javax.swing.JLabel lblLideres;
    private javax.swing.JLabel lblPErsonas;
    private javax.swing.JLabel lblRedes;
    private javax.swing.JPanel pn;
    // End of variables declaration//GEN-END:variables
}
