package com.bolivia.login.swing;
import java.awt.Cursor;
import java.awt.Dimension;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JLabel;
/**
 * @web http://www.jc-mouse.net/
 * @author Mouse
 */
public class JCPanelPass extends javax.swing.JPanel {

    /**
     * Creates new form JCPanelPass
     */
    public JCPanelPass() {
        initComponents();
        
       Dimension d = new Dimension(360,322);
       setSize(d);
       setVisible(true);
       lbError.setText("");
       cmdPrev.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
       btnPass.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    public JButton getButtonPass()
    {
        return this.btnPass;
    }
    
    public JLabel getCommand()
    {
        return this.cmdPrev;
    }
    
    public String getPassword()
    {
        return this.txtPass.getText();
    }
    
    public void showError(String value)
    {        
        lbError.setText(value);
    }
     
    public void setPhoto(Icon icon)
    {
        this.lbPhoto.setIcon(icon);
    } 
    
    public void setMail(String mail)
    {
        this.lbMail.setText(mail);
    }
    
    public void setUser(String name)
    {
        this.lbUser.setText(name);
        txtPass.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnPass = new com.bolivia.login.swing.JCButton();
        lbPhoto = new com.bolivia.login.swing.CLabel();
        txtPass = new com.bolivia.login.swing.JCTextField();
        lbUser = new javax.swing.JLabel();
        lbMail = new javax.swing.JLabel();
        lbError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmdPrev = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 247, 247));
        setLayout(new java.awt.GridBagLayout());

        btnPass.setText("Iniciar sesión");
        btnPass.setPreferredSize(new java.awt.Dimension(278, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        add(btnPass, gridBagConstraints);

        lbPhoto.setText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(lbPhoto, gridBagConstraints);

        txtPass.setPlaceholder("Contraseña");
        txtPass.setPreferredSize(new java.awt.Dimension(278, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 40, 0, 40);
        add(txtPass, gridBagConstraints);

        lbUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbUser.setForeground(new java.awt.Color(22, 22, 2));
        lbUser.setText("USUARIO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(lbUser, gridBagConstraints);

        lbMail.setForeground(new java.awt.Color(22, 22, 22));
        lbMail.setText("usuario@correo.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        add(lbMail, gridBagConstraints);

        lbError.setForeground(new java.awt.Color(221, 75, 57));
        lbError.setText("error");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(lbError, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(71, 135, 237));
        jLabel4.setText("¿Necesitas ayuda?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 16, 40);
        add(jLabel4, gridBagConstraints);

        cmdPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bolivia/login/res/ic_arrow.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        add(cmdPrev, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bolivia.login.swing.JCButton btnPass;
    private javax.swing.JLabel cmdPrev;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbMail;
    private com.bolivia.login.swing.CLabel lbPhoto;
    private javax.swing.JLabel lbUser;
    private com.bolivia.login.swing.JCTextField txtPass;
    // End of variables declaration//GEN-END:variables
}
