package com.bolivia.login.swing;
import java.awt.Cursor;
import java.awt.Dimension;
import javax.swing.JButton;
/**
 * @web http://www.jc-mouse.net/
 * @author Mouse
 */
public class JCPanelUser extends javax.swing.JPanel {

    /**
     * Creates new form JCPanelUser
     */
    public JCPanelUser() {
        initComponents();
        
        Dimension d = new Dimension(360,322);
        setSize(d);
        setVisible(true);
        btnNext.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lbError.setText("");
    }

    public JButton getButtonNext()
    {
        return this.btnNext;
    }
    
    public String getUser()
    {
        return this.txtUser.getText();
    }
    
    public void showError(String value)
    {        
        lbError.setText(value);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtUser = new com.bolivia.login.swing.JCTextField();
        btnNext = new com.bolivia.login.swing.JCButton();
        jLabel1 = new javax.swing.JLabel();
        cLabel1 = new com.bolivia.login.swing.CLabel();
        lbError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 247, 247));
        setLayout(new java.awt.GridBagLayout());

        txtUser.setPlaceholder("Introduce tu nombre de usuario");
        txtUser.setPreferredSize(new java.awt.Dimension(278, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(28, 40, 7, 40);
        add(txtUser, gridBagConstraints);

        btnNext.setText("Siguiente");
        btnNext.setPreferredSize(new java.awt.Dimension(278, 40));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(btnNext, gridBagConstraints);

        jLabel1.setForeground(new java.awt.Color(71, 135, 237));
        jLabel1.setText("¿Necesitas ayuda?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 25, 40);
        add(jLabel1, gridBagConstraints);

        cLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bolivia/login/res/ic_people.jpg"))); // NOI18N
        cLabel1.setText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(cLabel1, gridBagConstraints);

        lbError.setForeground(new java.awt.Color(221, 75, 57));
        lbError.setText("Error");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(lbError, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        
    }//GEN-LAST:event_btnNextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bolivia.login.swing.JCButton btnNext;
    private com.bolivia.login.swing.CLabel cLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbError;
    private com.bolivia.login.swing.JCTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
